HealthControllers:
    resource:
        path: ../src/Shared/Controller/
        namespace: App\Shared\Controller
    type: attribute
controllers:
    resource:
        path: ../src/Application/Controller/
        namespace: App\Application\Controller
    type: attribute
